### PR TITLE
Feature back last position

### PR DESCRIPTION
**Pull request by roaugusto**
Hi spgennard,

I tried to set all of your suggestions. I think that is ok. 
Feel free to change or recommend anything else.

Thanks

### CODE REVIEW

**Comment by spgennard** [comment]
Hi,

What is the advantage of this over the standard navigation functions eg;
   Alt+Left
  Alt+Right
?

**Comment by roaugusto** [comment]
Hi,

So, when I try to move for a section, and decided to move to another
section inside of this and decided to see one third section... and after
see what I wanted,  I would like to come back...

I don't know,  there's a standard navigation for that?

**Comment by spgennard** [comment]
After you jump to a section, you can jump back with ALT+LEFT ARROW and then move back with ALT+RIGHT ARROW.

(on PC)

**Comment by roaugusto** [comment]
Ah, ok..

I realized that on Mac the keys are different..

Anyway... Thanks...

**Comment by spgennard** [comment]
Given that both of us did not pick up the fact that navigation keystrokes exist, perhaps I should add a shortcut for it, so it is more visible.  What do you think?

**Comment by roaugusto** [comment]
I think so... I think is a good idea! This way is more explicit.

Em ter, 11 de jun de 2019 às 02:53, spgennard <notifications@github.com>
escreveu:

**Comment by roaugusto** [comment]
Hey spgennard,

One thing that I realized about the use the standard navigation, that is
the standard navigation occur over all the open documents.

So, if you want just back the positions over the same document, this
implementation has more sense.

But it is just a thing that  I realized. In the end, this implementation
has the same function that the standard navigation, but limited at one
single document and just for coming back in the positions.

Em ter, 11 de jun de 2019 às 09:01, Rodrigo Augusto Silva dos Santos <
ro.augusto@gmail.com> escreveu:

**Comment by GitMensch** [comment]
See [official doc about navigation](https://code.visualstudio.com/Docs/editor/editingevolved#_quick-file-navigation):

> Alternatively, you can use [Alt]+[Left] and [Alt]+[Right] to navigate between files and edit locations. If you are jumping around between different lines of the same file, these shortcuts allow you to navigate between those locations easily.

I do think it would be useful if vscode would have an option to: only switch between *edit* positions, too (maybe with a [SHIFT] modifier) but this should be implemented in vscode core to be available for any code (it is very bad if it just work with one file but not with the other).

**Comment by spgennard** [comment]
Do you want to raise this as an issue with vscode itself?   If so, can we close this merge request?

**Comment by spgennard** [comment]
let me know the issue number on vscode of the issue you have raised, closing this out

**Pull request closed without merging**
