### PR TITLE
move checkForConflicts to separate function

### PR DESCRIPTION
**Pull request by GitMensch**
and fix a typo in the message that pops up

### CODE REVIEW

**Comment by GitMensch** [comment]
@spgennard I suggest to add the old note "See View->Output->COBOL for more information" back, if you agree I can also add that before you possibly pull this.

**Comment by GitMensch** [comment]
@spgennard Conflicts were resolved. Are you ok with me adding the old note "See View->Output->COBOL for more information" back? Then I'd do that and squash the then 3 commits into one before the pull.

**Comment by GitMensch** [comment]
Conflicts resolved again, the new variant to always log with the option to directly show it is better than any previous one.

@spgennard So this PR is now just about what the title says: "move checkForConflicts to separate function" (a bit cleaner and no need to pass an extra argument to `initExtensionSearchPaths()` which actually has nothing to do with search paths.
Please drop a note if you want to have a "clean one single commit", in this case I'll open a new PR, otherwise feel free to merge as-is.

**Comment by spgennard** [comment]
> initExtensionSearchPaths() which actually has nothing to do with search paths

So, what is this code?


```typescript
   fileSearchDirectory.length = 0;

    const extsdir = config.copybookdirs;
    invalidSearchDirectory = config.invalid_copybookdirs;
    invalidSearchDirectory.length = 0;

    // step 1 look through the copybook default dirs for "direct" paths and include them in search path
    for (const ddir of extsdir) {
        if (config.disable_unc_copybooks_directories && COBOLFileUtils.isNetworkPath(ddir)) {
            logMessage(" Copybook directory " + ddir + " has been marked as invalid, as it is a unc filename");
            invalidSearchDirectory.push(ddir);
        }
        else if (COBOLFileUtils.isDirectPath(ddir)) {
            logWarningMessage(` non portable copybook directory ${ddir} defined`);
            if (workspace !== undefined && getWorkspaceFolders() !== undefined) {
                if (VSCOBOLFileUtils.isPathInWorkspace(ddir) === false) {
                    if (COBOLFileUtils.isNetworkPath(ddir)) {
                        logMessage(" The directory " + ddir + " for performance should be part of the workspace");
                    }
                }
            }

            const startTime = performance_now();
            if (isDirectory(ddir)) {
                const totalTimeInMS = performance_now() - startTime;
                const timeTaken = totalTimeInMS.toFixed(2);
                if (totalTimeInMS <= 2000) {
                    fileSearchDirectory.push(ddir);
                } else {
                    logMessage(" Slow copybook directory dropped " + ddir + " as it took " + timeTaken + "ms");
                    invalidSearchDirectory.push(ddir);
                }
            } else {
                invalidSearchDirectory.push(ddir);
            }
        }
    }

    // step 2
    const ws = getWorkspaceFolders();
    if (ws !== undefined) {
        for (const folder of ws) {
            // place the workspace folder in the copybook path

            fileSearchDirectory.push(folder.uri.fsPath);

            /* now add any extra directories that are below this workspace folder */
            for (const extdir of extsdir) {
                try {
                    if (COBOLFileUtils.isDirectPath(extdir) === false) {
                        const sdir = path.join(folder.uri.fsPath, extdir);

                        if (isDirectory(sdir)) {
                            if (COBOLFileUtils.isNetworkPath(sdir) && VSCOBOLFileUtils.isPathInWorkspace(sdir) === false) {
                                logMessage(" The directory " + sdir + " for performance should be part of the workspace");
                            }

                            fileSearchDirectory.push(sdir);
                        } else {
                            invalidSearchDirectory.push(sdir);
                        }
                    }
                }
                catch (e) {
                    logException("dir", e);
                }
            }
        }
    }

    fileSearchDirectory = fileSearchDirectory.filter((elem, pos) => fileSearchDirectory.indexOf(elem) === pos);
    invalidSearchDirectory = invalidSearchDirectory.filter((elem, pos) => invalidSearchDirectory.indexOf(elem) === pos);
}

```

**Comment by GitMensch** [comment]
That code is perfectly handling search paths - which is the reason why I've moved the part that does not has to do something with that out to a separate function.

**Comment by GitMensch** [comment]
Close due to "merge in" with b8fbfcf7d6625d56b52aa9030a8eb729504d432f.

**Pull request closed without merging**
